### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by taufique74** [ShulinCao/OpenNRE-PyTorch#22]
Reading training data...
Finish reading
Reading testing data...
Finish reading
Initializing training model...
Finish initializing
Epoch 0 starts...
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    con.train()
  File "/home/peyash/nlp/OpenNRE-PyTorch/config/Config.py", line 248, in train
    loss = self.train_one_step()
  File "/home/peyash/nlp/OpenNRE-PyTorch/config/Config.py", line 214, in train_one_step
    loss, _output = self.trainModel()
  File "/home/peyash/anaconda3/envs/p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/peyash/nlp/OpenNRE-PyTorch/models/Model.py", line 22, in forward
    sen_embedding = self.encoder(embedding)
  File "/home/peyash/anaconda3/envs/p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/peyash/nlp/OpenNRE-PyTorch/networks/encoder.py", line 49, in forward
    x = self.cnn(embedding)
  File "/home/peyash/anaconda3/envs/p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/peyash/nlp/OpenNRE-PyTorch/networks/encoder.py", line 21, in forward
    return self.cnn(embedding)
  File "/home/peyash/anaconda3/envs/p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/peyash/anaconda3/envs/p27/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/peyash/anaconda3/envs/p27/lib/python2.7/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

Any hint why is this happening?

**Comment by Christiannov** [comment]
@taufique74 I've met the same error. Have you solved it?
